services:
  frontend:
    build:
      context: "./sp-frontend"
      dockerfile: "./Dockerfile"
  backend:
    build:
      context: "./sp-backend"
      dockerfile: "./Dockerfile"
  backend-ws:
    build:
      context: "."
      dockerfile: "./Dockerfile-ws"


